"""Seed initial residents (utentes) of Centro Social de Brito.
Loaded once at startup if the utentes collection is empty.
Names extracted from official lists provided by the institution.
"""

UTENTES_SEED = {
    "erpi_sede": [
        "Adelaide Jesus Batista",
        "Agostinho de Jesus Ribeiro da Silva",
        "Agostinho Domingos Gomes",
        "Albertina Marques de Carvalho",
        "Ana de Sousa",
        "Ana Rodrigues Faria",
        "Antonia Engrácia Dias da Silva Salgado",
        "Antónia Marques Oliveira",
        "António Cunha dos Santos",
        "Antonio Peixoto da Silva",
        "Balbina dos Prazeres Ferreira Pinto da Silva",
        "Belém da Silva Lopes",
        "Camila Correia",
        "Carolina Rosa Antunes Fernandes",
        "Clara de Castro",
        "Domingos Neves Dias",
        "Eduardo de Almeida e Silva",
        "Emilia Salgado Mendes",
        "Engrácia Mota Gonçalves",
        "Eva Silva Teixeira",
        "Ezequiel Nogueira Leite",
        "Gracinda Alves Mendes",
        "João Ferreira",
        "João Freitas Nogueira Leite",
        "Joaquim Vieira Gonçalves",
        "Joaquina Ferreira Mendes",
        "José Gomes Magalhães",
        "Júlia Teixeira Guimarães",
        "Laurinda da Costa Pereira",
        "Lúcia de Sousa Fernandes",
        "Lucinda Alves",
        "Manuel Alcino Dias de Barros",
        "Manuel da Silva e Sousa",
        "Manuel Francisco Freitas da Silva Teles",
        "Manuel Joaquim Sousa da Silva",
        "Manuel Lamas Fernandes",
        "Manuel Machado de Oliveira",
        "Manuel Mendes de Freitas",
        "Manuel Pereira Ribeiro",
        "Manuel Silva",
        "Maria Adélia Couto Costa",
        "Maria Amélia Gonçalves Ribeiro de Sousa",
        "Maria Antónia Pereira Fernandes da Costa",
    ],
    "erpi_parais": [
        "Adão da Silva Matos",
        "Adelina da Mota Freitas",
        "Adelino da Silva Pereira Machado",
        "Alexandre Lemos",
        "Álvaro Ferreira",
        "Ana de Castro Batista",
        "Ana Marques Pereira",
        "Ana Silva Ferreira",
        "António de Araújo Fernandes",
        "António Marques",
        "António Martins Pereira",
        "Delfina da Cunha Gomes",
        "Emília do Rosário Machado de Faria",
        "Felicidade Silva Cunha",
        "Fernando Augusto Teles Alves",
        "Francisco Mendes",
        "João Carlos Martins Oliveira",
        "João Martins da Silva",
        "Joaquim Machado Silva",
        "Joaquina de Oliveira Cunha",
        "José Silva",
        "Laura Bravo Albuquerque",
        "Laurinda da Silva Almeida da Rocha",
        "Leopoldina Ferreira Araújo",
        "Manuel Augusto da Silva",
        "Manuel Mendes",
        "Manuel Teixeira de Faria",
        "Maria Angelina Pereira Alva",
        "Maria Cândida Rodrigues Silva",
        "Maria da Conceição Pereira Vieira",
        "Maria da Conceição Fernandes Castro",
        "Maria da Conceição Pereira",
        "Maria da Silva",
        "Maria do Carmo Ribeiro de Castro",
        "Maria do Carmo Ribeiro Leite",
        "Maria dos Prazeres Almeida",
        "Maria Emília Ferreira",
        "Maria Fernandes",
        "Maria Fernandina Brandão Machado São Pedro",
        "Maria Gomes Rodrigues",
        "Maria Irene Marques Pereira da Silva",
        "Maria Isabel Amaral Ferreira Gonçalves",
        "Maria Isabel Ferreira da Cunha",
    ],
    "lar_residencial": [
        "Acácio Augusto de Sousa Vieira",
        "Ana Catarina Ribeiro de Sousa",
        "Ana Maria de Carvalho Henriques",
        "Ana Maria de Castro Carvalho",
        "Ana Rita Fernandes Pinto",
        "Carla da Conceição de Castro Carvalho",
        "Clemente Marques Ferreira",
        "Fábio Filipe Pedrosa Guedes",
        "Francisco Filipe Costa Ribeiro",
        "Joana Isabel Pinto Costa",
        "João António Marques da Silva",
        "João Silva Santos",
        "Joaquim Manuel da Silva Machado",
        "Jonathan Kallym Pagno Carrilho",
        "José Manuel Freitas da Silva",
        "Liliana Odete Pinto Faria",
        "Luís Miguel Vaz Guimarães",
        "Manuel António Mendes Fernandes",
        "Manuel Filipe Castro Pereira",
        "Margarida Carvalho Macieira",
        "Maria Arminda Ferreira da Silva",
        "Maria Assunção Fernandes Salgado",
        "Maria Aurora Freitas de Oliveira",
        "Maria Goreti Martins Ribeiro",
        "Maria Teresa Vieira Ferreira",
        "Patricio Jorge Correia Gomes",
        "Rita Helena Abrantes Guedes Ruão Cunha",
        "Rute Marlene Machado Oliveira",
        "Tiago Manuel Ferreira Almeida",
    ],
}
